apiVersion: kspec.io/v1alpha1
kind: Policy
metadata:
  name: example-policy
  title: Example Local Security Policy
  version: 0.1.0
groups:
  - title: System Integrity
    checks:
      - id: check-go-mod-exists
        title: Ensure go.mod exists
        resource: file
        config:
           path: ./go.mod
        query: resource.exists == true
        severity: critical

      - id: check-go-mod-not-dir
        title: Ensure go.mod is not a directory
        resource: file
        config:
           path: ./go.mod
        query: resource.is_dir == false
        severity: high

  - title: Software Compliance
    checks:
      - id: check-go-installed
        title: Ensure Go is installed
        resource: package
        config:
           name: go
        query: resource.installed == true && resource.version.startsWith("1.")
        severity: medium
